In [202]:
import pandas as pd
import numpy as np

# Auswertung für: MessdatenZeit-Confidence.csv
Daten wurden gegen 9:00 Uhr aufgenommen

Labels der echten Objekte generieren

In [203]:

df1 = 'Labels.xlsx'
# Excel-Datei einlesen
df = pd.read_excel(df1)  # Optional: sheet_name="Blattname"

# In CSV speichern
df.to_csv("Labels.csv", index=False, encoding='utf-8')

In [204]:
label = pd.read_csv('Labels.csv')
label.head(12)
messreihe = pd.read_csv('messdatenZeit-Confidence.csv')

df1 = pd.concat([label, messreihe], axis=1)
df1 =  df1.replace(5968.0, 5.968)
#data.to_csv('messdatenConfidence.csv', index= False)
df1.head()

,Objekt,maxSide,minSide,Label,confidence_YOLO,confidence,maxSize [cm],min [cm],ElapsedTime [s]
0,Würfel,2.3,2.3,dog,0.10,0.762581,0.000000,0.000000,18.025399
1,Würfel,2.3,2.3,dog,0.15,0.745450,0.000000,0.000000,4.623249
2,Würfel,2.3,2.3,cell phone,0.20,0.786992,2.760800,2.645559,30.828532
3,Würfel,2.3,2.3,donut,0.25,0.405728,3.346720,3.270890,10.033874
4,Würfel,2.3,2.3,donut,0.30,0.680684,3.647697,3.292640,4.891258

Erkennungsgeschwindigkeit nach Confidence

In [205]:
# # Gruppieren nach confidence und Mittelwert der Zeit berechnen
# data_mittelwertConfidence = data.groupby('confidence_YOLO')['ElapsedTime [s]'].mean().reset_index()
# data_mittelwertConfidence.head(5)

Daten nach Konfidenz Schwellenwert sortieren und Zeit angeben lassen

In [206]:
df1_mittelwertZeit = df1.groupby('confidence_YOLO')['ElapsedTime [s]'].agg(
    Dauer_Durchschnitt='mean',
    Standardabweichung='std',
    Minimum='min', 
    Maximum='max'
).reset_index()
df1_mittelwertZeit = df1_mittelwertZeit.sort_values(
    by='Dauer_Durchschnitt',
    ascending=True
)
df1_mittelwertZeit

,confidence_YOLO,Dauer_Durchschnitt,Standardabweichung,Minimum,Maximum
4,0.30,5.736147,1.539017,3.409861,7.695181
5,0.35,8.623971,5.032921,3.606938,17.720841
8,0.50,10.363089,9.610631,3.474893,26.011741
3,0.25,10.456086,11.105329,3.043856,32.410618
6,0.40,10.780514,10.596129,4.163195,30.866740
2,0.20,11.754973,9.533251,5.176346,30.828532
7,0.45,19.087691,24.923577,2.859687,63.399841
0,0.10,21.838773,15.197010,7.171826,48.073318
1,0.15,23.133668,24.959570,4.318140,71.177494
9,0.55,24.758591,26.712952,3.286418,58.440272

In [207]:
objekt_counts = df1['Objekt'].value_counts()

# Ausgabe
print(objekt_counts)

Objekt
Würfel                   10
batterie                 10
ball                     10
Metallplatte             10
Schaumstoff Ding         10
Schraubenzieher           9
Schraubenzieher Griff     1
Name: count, dtype: int64

Abweichungen der Dimensionen hinzufügen

In [208]:

# Neue Spalten berechnen
#df1['Abweichung_maxSide [cm]'] = abs(df1['maxSide'] - df1['maxSize [cm]'])
#df1['Abweichung_minSide [cm]'] = abs(df1['minSide'] - df1['min [cm]'])
df1['Abweichung Gesamt'] = np.sqrt((df1['maxSide']-df1['maxSize [cm]'])**2 + (df1['minSide']-df1['min [cm]'])**2 )
df1.head()

,Objekt,maxSide,minSide,Label,confidence_YOLO,confidence,maxSize [cm],min [cm],ElapsedTime [s],Abweichung Gesamt
0,Würfel,2.3,2.3,dog,0.10,0.762581,0.000000,0.000000,18.025399,3.252691
1,Würfel,2.3,2.3,dog,0.15,0.745450,0.000000,0.000000,4.623249,3.252691
2,Würfel,2.3,2.3,cell phone,0.20,0.786992,2.760800,2.645559,30.828532,0.575975
3,Würfel,2.3,2.3,donut,0.25,0.405728,3.346720,3.270890,10.033874,1.427673
4,Würfel,2.3,2.3,donut,0.30,0.680684,3.647697,3.292640,4.891258,1.673805

Daten nach Konfidenz Schwellenwert sortieren und Dimensonsabweichungen angeben lassen

In [209]:
data_mittelwertAbweichung = df1.groupby('confidence_YOLO')['Abweichung Gesamt'].agg(
    Abweichung_Durchschnitt='mean',
    Standardabweichung='std',
    Minimum='min', 
    Maximum='max'
).reset_index()

data_mittelwertAbweichung = data_mittelwertAbweichung.sort_values(
    by='Abweichung_Durchschnitt',
    ascending=True
)
data_mittelwertAbweichung

,confidence_YOLO,Abweichung_Durchschnitt,Standardabweichung,Minimum,Maximum
4,0.30,1.662879,1.214366,0.740582,4.050691
5,0.35,1.758318,1.838570,0.857732,5.481308
2,0.20,1.802765,2.154384,0.575975,6.146834
3,0.25,1.938664,2.118244,0.794470,6.229693
6,0.40,1.947826,2.386974,0.506940,6.789251
0,0.10,1.982234,1.225784,0.760825,3.561054
9,0.55,2.111435,2.627097,0.784613,7.458992
1,0.15,2.134893,1.727263,0.669724,4.934043
7,0.45,2.407584,2.197438,0.901962,6.651253
8,0.50,3.017838,5.134604,0.669019,13.491832

Abweichung max Side

In [210]:
# data_mittelwertAbweichungX = df1.groupby('confidence_YOLO')['Abweichung_maxSide [cm]'].agg(
#     maxSide_Abweichung_Durchschnitt='mean',
#     Standardabweichung='std',
#     Minimum='min', 
#     Maximum='max'
# ).reset_index()
# data_mittelwertAbweichungX = data_mittelwertAbweichungX.sort_values(
#     by = 'maxSide_Abweichung_Durchschnitt',
#     ascending= True
# )
# data_mittelwertAbweichungX = data_mittelwertConfidence.sort_values(
#     by='Abweichung_Durchschnitt',
#     ascending=True
# )
# data_mittelwertAbweichungX

Abweichung minSide

In [211]:
# data_mittelwertAbweichungY = df1.groupby('confidence_YOLO')['Abweichung_minSide [cm]'].agg(
#     minSide_Abweichung_Durchschnitt='mean',
#     Standardabweichung='std',
#     Minimum='min', 
#     Maximum='max'
# ).reset_index()
# data_mittelwertAbweichungY = data_mittelwertAbweichungY.sort_values(
#     by = 'minSide_Abweichung_Durchschnitt',
#     ascending= True
# )
# data_mittelwertAbweichungY

# Fazit

Da Fehler und Erkennungszeit bei einem Schwellwert von 0,35 am geringesten sind (für Stabilitätskriterium von 1,5 Sekunden) wird dieser als Schwellwert für die Konfidenz gewählt

# Auswertung für großes Datenset: messdatenZeit-Confidence1.1
Wurde gegen 12:00 Uhr aufgenommen

In [212]:
import pandas as pd
import numpy as np

Datenset lesen

In [213]:
df2 =pd.read_csv("messdatenZeit-Confidence1.1.csv")
df2 = df2.rename(columns={'confidence_YOLO': 'Schwellwert'})
df2.head()

,Objekt,Yolo Label,Schwellwert,confidence,xSize [cm],ySize [cm],ElapsedTime [s]
0,Würfel,remote,0.15,0.152611,2.752618,2.698562,10.891751
1,Würfel,remote,0.15,0.487260,3.110705,2.927988,3.045505
2,Würfel,remote,0.15,0.675513,3.124762,3.027404,2.926307
3,Würfel,remote,0.15,0.535611,3.205923,3.149009,2.574978
4,Würfel,cell phone,0.15,0.176638,3.262349,3.247328,2.951631

gemessene Dimensonen hinzufügen

In [214]:
referenzwerte = {
    'Würfel': {'max': 2.3, 'min': 2.3},
    'Ball': {'max': 5.968, 'min': 5.968},
    'Metallplatte': {'max': 19.0, 'min': 11.0},
    'Schraubenzieher': {'max': 9.5, 'min': 3.0},
    'Schraubenzieher Griff': {'max': 9.5, 'min': 3.0},
    'Schaumstoff Ding': {'max': 38.0, 'min': 4.5}
}

In [215]:
df2['maxSide'] = df2['Objekt'].map(lambda x: referenzwerte.get(x, {}).get('max', None))
df2['minSide'] = df2['Objekt'].map(lambda x: referenzwerte.get(x, {}).get('min', None))
df2.head()

,Objekt,Yolo Label,Schwellwert,confidence,xSize [cm],ySize [cm],ElapsedTime [s],maxSide,minSide
0,Würfel,remote,0.15,0.152611,2.752618,2.698562,10.891751,2.3,2.3
1,Würfel,remote,0.15,0.487260,3.110705,2.927988,3.045505,2.3,2.3
2,Würfel,remote,0.15,0.675513,3.124762,3.027404,2.926307,2.3,2.3
3,Würfel,remote,0.15,0.535611,3.205923,3.149009,2.574978,2.3,2.3
4,Würfel,cell phone,0.15,0.176638,3.262349,3.247328,2.951631,2.3,2.3

In [216]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Objekt           500 non-null    object
 1   Yolo Label       500 non-null    object
 2   Schwellwert      500 non-null    float64
 3   confidence       500 non-null    float64
 4   xSize [cm]       500 non-null    float64
 5   ySize [cm]       500 non-null    float64
 6   ElapsedTime [s]  500 non-null    float64
 7   maxSide          500 non-null    float64
 8   minSide          500 non-null    float64
dtypes: float64(7), object(2)
memory usage: 35.3+ KB

Zeit bis Objekt als stabil erkannt wurde

In [217]:
big_data_mittelwertZeit = df2.groupby('Schwellwert')['ElapsedTime [s]'].agg(
    Dauer_Durchschnitt='mean',
    Standardabweichung='std',
    Minimum='min', 
    Maximum='max'
).reset_index()
big_data_mittelwertZeit = big_data_mittelwertZeit.sort_values(
    by='Dauer_Durchschnitt',
    ascending=True
)
big_data_mittelwertZeit

   Schwellwert  Dauer_Durchschnitt  Standardabweichung   Minimum     Maximum
1         0.20            5.452349            6.123679  2.174299   42.562238
0         0.15            5.463149            4.698560  2.112127   22.789821
2         0.25            5.611587            3.146228  2.351067   15.650962
3         0.30            6.099973            4.037882  2.657470   28.341075
4         0.35            6.165704            4.213501  2.604727   25.552234
5         0.40            7.719261            7.342345  2.351059   48.910710
8         0.55            8.648557            9.518195  2.501942   52.591391
7         0.50           10.418725           10.842548  2.525095   64.853440
6         0.45           11.111946           12.618446  2.381646   69.777900
9         0.60           12.913255           17.799786  2.495255  108.160520

Dimensons-Abweichungen berechnen

In [238]:
df2['Reale_Diagonale [cm]'] = np.sqrt(df2['maxSide']**2 + df2['minSide']**2)
df2['Aweichung maxSide[cm]'] = np.sqrt((df2['maxSide'] - df2['xSize [cm]'])**2 )
df2['Aweichung minSide[cm]'] = np.sqrt( (df2['minSide'] - df2['ySize [cm]'])**2)
df2['Abweichung [cm]'] = np.sqrt((df2['maxSide'] - df2['xSize [cm]'])**2 + (df2['minSide'] - df2['ySize [cm]'])**2)
df2['Abweichung [%]'] = (df2['Abweichung [cm]'] / df2['Reale_Diagonale [cm]']) * 100

df2.head()

,Objekt,Yolo Label,Schwellwert,confidence,xSize [cm],ySize [cm],ElapsedTime [s],maxSide,minSide,Reale_Diagonale [cm],Abweichung [cm],Abweichung [%],Aweichung maxSide[cm],Aweichung minSide[cm]
0,Würfel,remote,0.15,0.152611,2.752618,2.698562,10.891751,2.3,2.3,3.252691,0.603088,18.541191,0.452618,0.398562
1,Würfel,remote,0.15,0.487260,3.110705,2.927988,3.045505,2.3,2.3,3.252691,1.025481,31.527143,0.810705,0.627988
2,Würfel,remote,0.15,0.675513,3.124762,3.027404,2.926307,2.3,2.3,3.252691,1.099704,33.809047,0.824762,0.727404
3,Würfel,remote,0.15,0.535611,3.205923,3.149009,2.574978,2.3,2.3,3.252691,1.241577,38.170769,0.905923,0.849009
4,Würfel,cell phone,0.15,0.176638,3.262349,3.247328,2.951631,2.3,2.3,3.252691,1.350387,41.515993,0.962349,0.947328

Nach Aweichung sorrtieren

In [240]:
# Gruppieren nach Schwellwert
data_mittelwertAbweichung = df2.groupby('Schwellwert')['Abweichung [%]'].agg(
    Abweichung_Durchschnitt='mean',
    Standardabweichung='std',
)

# Nach durchschnittlicher Abweichung sortieren
data_mittelwertAbweichung = data_mittelwertAbweichung.sort_values(
    by='Abweichung_Durchschnitt',
    ascending=True
).reset_index()
data_mittelwertAbweichung

   Schwellwert  Abweichung_Durchschnitt  Standardabweichung
0         0.35                12.015289            7.439322
1         0.25                12.362853            6.586021
2         0.55                13.025936            9.967610
3         0.40                13.067246            9.233349
4         0.30                13.737468           10.540272
5         0.45                14.744877            9.602640
6         0.20                14.978464           13.849145
7         0.60                15.051509           11.041618
8         0.50                17.124591           11.706013
9         0.15                19.033577           24.560862

# Datenset groß (nur mit K-Wert von 35)

YOLO mit Schwellwert = 0.35 herausfiltern

In [220]:
gefiltert35 = df2[df2['Schwellwert'].isin([0.35])]

gefiltert35.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 40 to 449
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Objekt                50 non-null     object
 1   Yolo Label            50 non-null     object
 2   Schwellwert           50 non-null     float64
 3   confidence            50 non-null     float64
 4   xSize [cm]            50 non-null     float64
 5   ySize [cm]            50 non-null     float64
 6   ElapsedTime [s]       50 non-null     float64
 7   maxSide               50 non-null     float64
 8   minSide               50 non-null     float64
 9   Reale_Diagonale [cm]  50 non-null     float64
 10  Abweichung [cm]       50 non-null     float64
 11  Abweichung [%]        50 non-null     float64
dtypes: float64(10), object(2)
memory usage: 5.1+ KB

Unterschiede der Objekte (Konfidenz- 0.35)

In [221]:
# Zeit-Statistiken
df_Zeit = gefiltert35.groupby('Objekt')['ElapsedTime [s]'].agg(
    Durchschnitt_Zeit='mean',
    Standardabweichung_Zeit='std',
)

# Abweichung in Prozent
df_Abw_Prozent = gefiltert35.groupby('Objekt')['Abweichung [%]'].agg(
    Durchschnitt_Abweichung_Prozent='mean',
)

# Abweichung in cm
df_Abw_cm = gefiltert35.groupby('Objekt')['Abweichung [cm]'].agg(
    Durchschnitt_Abweichung_cm='mean',
)

# Alles zusammenführen
data_gesamt = df_Zeit.merge(df_Abw_cm, on='Objekt') \
                     .merge(df_Abw_Prozent, on='Objekt') \
                     .reset_index()

# Sortierung
data_gesamt = data_gesamt.sort_values(by='Durchschnitt_Abweichung_Prozent', ascending=True)

# Ausgabe
data_gesamt

,Objekt,Durchschnitt_Zeit,Standardabweichung_Zeit,Durchschnitt_Abweichung_cm,Durchschnitt_Abweichung_Prozent
2,Schaumstoff Ding,7.911065,4.435779,2.192463,5.729603
1,Metallplatte,4.441765,1.021754,1.842303,8.391462
0,Ball,5.374182,2.078328,0.745158,8.828858
3,Schraubenzieher,8.112295,7.280997,1.582602,15.885699
4,Würfel,4.989213,2.339810,0.690898,21.240823

Einzelne Abweichungen analysieren

In [260]:
dimensions = df2[['Objekt', 'Schwellwert','maxSide', 'Aweichung maxSide[cm]', 'minSide',  'Aweichung minSide[cm]']]
dimensions_grouped = (
    df2
    .groupby('Objekt')[['Aweichung maxSide[cm]', 'Aweichung minSide[cm]']]
    .mean()
    .reset_index()
    .round(2)  # optional: auf zwei Dezimalstellen runden
)

dimensions_grouped

             Objekt  Aweichung maxSide[cm]  Aweichung minSide[cm]
0              Ball                   0.56                   0.65
1      Metallplatte                   0.66                   1.73
2  Schaumstoff Ding                   0.74                   3.03
3   Schraubenzieher                   1.28                   1.20
4            Würfel                   0.64                   0.49

## Grund für Zeit herausfinden

YOLO-Labels für Objekte

Anzahl verschiedener Labels

In [222]:
import pandas as pd


df5 = gefiltert35.copy()
# # Ausgabe
# print(anzahl_labels_pro_objekt)
yolo_labels_details = df5.groupby("Objekt")["Yolo Label"].agg(['nunique']).reset_index()
#yolo_labels_details.columns = ["Objekt", "YOLO_Labels", "Anzahl_YOLO_Labels"]

print(yolo_labels_details)

             Objekt  nunique
0              Ball        2
1      Metallplatte        1
2  Schaumstoff Ding        1
3   Schraubenzieher        2
4            Würfel        2

Labels/Objekt

In [223]:

yolo= df5.groupby("Objekt")["Yolo Label"].agg(['unique']).reset_index()
# Anzeige-Einstellungen anpassen
pd.set_option("display.max_colwidth", None)

yolo

             Objekt                unique
0              Ball      [donut, frisbee]
1      Metallplatte              [remote]
2  Schaumstoff Ding               [knife]
3   Schraubenzieher   [scissors, frisbee]
4            Würfel  [carrot, cell phone]

Anzahl Labels/Objekt

In [224]:
label_counts = pd.crosstab(df5["Objekt"], df5["Yolo Label"])

# Ausgabe
print(label_counts)

Yolo Label        carrot  cell phone  donut  frisbee  knife  remote  scissors
Objekt
Ball                   0           0      5        5      0       0         0
Metallplatte           0           0      0        0      0      10         0
Schaumstoff Ding       0           0      0        0     10       0         0
Schraubenzieher        0           0      0        4      0       0         6
Würfel                 2           8      0        0      0       0         0

Nach Yolo-Confidence sortieren

In [225]:
conf= df5.groupby("Objekt")["confidence"].agg(
    Mittelwert = 'mean',
    StdA = 'std'
).reset_index()
conf

             Objekt  Mittelwert      StdA
0              Ball    0.423526  0.066939
1      Metallplatte    0.637968  0.133596
2  Schaumstoff Ding    0.477334  0.111086
3   Schraubenzieher    0.555035  0.136215
4            Würfel    0.451555  0.081544

In [226]:
size = df5.groupby('Objekt')['Reale_Diagonale [cm]'].agg(
    d = 'mean'
)
size

                          d
Objekt
Ball               8.440027
Metallplatte      21.954498
Schaumstoff Ding  38.265520
Schraubenzieher    9.962429
Würfel             3.252691

In [227]:
yolo= df5.groupby("Yolo Label")["confidence"].agg(
    mean = 'mean',
    std = 'std'
    ).reset_index()
# Anzeige-Einstellungen anpassen
pd.set_option("display.max_colwidth", None)

yolo

   Yolo Label      mean       std
0      carrot  0.400210  0.043705
1  cell phone  0.464392  0.085644
2       donut  0.441613  0.083072
3     frisbee  0.462171  0.131919
4       knife  0.477334  0.111086
5      remote  0.637968  0.133596
6    scissors  0.569667  0.118507

Unterschiede der Zeit

In [228]:
data_ObjektZeit = gefiltert35.groupby('Objekt')['ElapsedTime [s]'].agg(
    Durchschnitt_Zeit='mean',
    Standardabweichung='std',
    Minimum='min', 
    Maximum='max'
).reset_index()

# Nach durchschnittlicher Abweichung sortieren
data_ObjektZeit = data_ObjektZeit.sort_values(
    by='Durchschnitt_Zeit',
    ascending=True
)
data_ObjektZeit

,Objekt,Durchschnitt_Zeit,Standardabweichung,Minimum,Maximum
1,Metallplatte,4.441765,1.021754,3.227495,6.352299
4,Würfel,4.989213,2.339810,2.604727,8.433123
0,Ball,5.374182,2.078328,2.685750,9.484767
2,Schaumstoff Ding,7.911065,4.435779,4.635944,19.997053
3,Schraubenzieher,8.112295,7.280997,2.659599,25.552234

# Kleines Datenset ~9:00 Uhr mit großem Datenset ~12:00 Uhr vergleichen

Objekte die nicht in großem Datenset sind rausziehen

In [229]:
label = pd.read_csv('Labels.csv')
label.head(12)
messreihe = pd.read_csv('messdatenZeit-Confidence.csv')

df1 = pd.concat([label, messreihe], axis=1)
df1 =  df1.replace(5968.0, 5.968)
#data.to_csv('messdatenConfidence.csv', index= False)




df_klein = df1.copy()
df_klein = df_klein[df_klein['Objekt'] != 'batterie']
df_klein['Objekt'] = df_klein['Objekt'].replace('Schraubenzieher Griff', 'Schraubenzieher')

print(df_klein.groupby('Objekt')['ElapsedTime [s]'].agg(
    DurchschnitZeit = 'mean',
    stdTime = 'std'
).reset_index())
df_klein = df_klein.groupby('confidence_YOLO')['ElapsedTime [s]'].agg(
    DurchschnitZeit = 'mean',
    stdTime = 'std'
).reset_index()
df_klein

             Objekt  DurchschnitZeit    stdTime
0      Metallplatte         5.416650   3.275316
1  Schaumstoff Ding        26.704044  19.905738
2   Schraubenzieher        22.345515  16.353278
3            Würfel         9.238395   8.740722
4              ball         5.046556   1.554365

   confidence_YOLO  DurchschnitZeit    stdTime
0             0.10        16.591864   9.067028
1             0.15        13.524903   9.287755
2             0.20        12.583438  10.414217
3             0.25        11.539892  12.056146
4             0.30         5.344340   1.345130
5             0.35         6.804596   2.614757
6             0.40        12.051101  11.324288
7             0.45        21.794066  26.861634
8             0.50        11.387446  10.372341
9             0.55        25.880674  29.707478

Große Liste komprimieren, sodass nur erster Wert von Objekt/Confidnce in df ist

In [230]:
# c = []
# i = 2
# for n in range(0,60):
#     #print(i)
#     c.append(i)
#     i += 10

c = list(range(2, 500, 10))

df_komprimiert = df2.iloc[c].reset_index(drop=True)
df_komprimiert = df_komprimiert.groupby('Schwellwert')['ElapsedTime [s]'].agg(
    Durchschnitt_s = 'mean',
    std = 'std'
).reset_index()
df_komprimiert

   Schwellwert  Durchschnitt_s        std
0         0.15        6.446334   7.112849
1         0.20       11.143554  17.608005
2         0.25        4.426743   2.799954
3         0.30        4.884276   2.254218
4         0.35        8.560187   4.096123
5         0.40        5.919008   3.982512
6         0.45        8.518143   5.392532
7         0.50       15.560410  11.705078
8         0.55        8.002124   4.027311
9         0.60       25.555537  46.257559

Zusammenbringer beider Dfs

In [231]:
df_vergleich = pd.merge(
    df_komprimiert,         # 🔹 Erster DataFrame
    df_klein,                # 🔹 Zweiter DataFrame
    left_on="Schwellwert",  # 🔹 Spalte im ersten DF, die als Verknüpfung verwendet wird
    right_on="confidence_YOLO",  # 🔹 Entsprechende Spalte im zweiten DF
    how="inner"             # 🔹 Verknüpfungsart: nur Übereinstimmungen (wie INNER JOIN in SQL)
)
df_vergleich = df_vergleich.drop(columns=['confidence_YOLO', 'std', 'stdTime'])
df_vergleich = df_vergleich.rename(columns={'Durchschnitt_s': 'Mean[s] 12:00', 'DurchschnitZeit': 'Mean[s] 9:00'})
df_vergleich = df_vergleich[["Schwellwert", "Mean[s] 9:00", "Mean[s] 12:00"]]

df_vergleich

   Schwellwert  Mean[s] 9:00  Mean[s] 12:00
0         0.15     13.524903       6.446334
1         0.20     12.583438      11.143554
2         0.25     11.539892       4.426743
3         0.30      5.344340       4.884276
4         0.35      6.804596       8.560187
5         0.40     12.051101       5.919008
6         0.45     21.794066       8.518143
7         0.50     11.387446      15.560410
8         0.55     25.880674       8.002124

In [232]:
df_vergleich['Differenz [s]'] = (df_vergleich['Mean[s] 9:00']  - df_vergleich['Mean[s] 12:00']) 
df_vergleich

   Schwellwert  Mean[s] 9:00  Mean[s] 12:00  Differenz [s]
0         0.15     13.524903       6.446334       7.078569
1         0.20     12.583438      11.143554       1.439884
2         0.25     11.539892       4.426743       7.113149
3         0.30      5.344340       4.884276       0.460065
4         0.35      6.804596       8.560187      -1.755591
5         0.40     12.051101       5.919008       6.132093
6         0.45     21.794066       8.518143      13.275923
7         0.50     11.387446      15.560410      -4.172964
8         0.55     25.880674       8.002124      17.878550

In [233]:
df10 = pd.read_csv('Zeiten.csv')
#df1.rename(columns={df.columns[0]: 'Objekt'}, inplace=True)

df10.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Objekt           32 non-null     object
 1   Label            32 non-null     object
 2   confidence_YOLO  32 non-null     float64
 3   confidence       32 non-null     float64
 4   xSize [cm]       32 non-null     float64
 5   ySize [cm]       32 non-null     float64
 6   ElapsedTime [s]  32 non-null     float64
dtypes: float64(5), object(2)
memory usage: 1.9+ KB

In [234]:
df10 = df10.groupby('Objekt')['ElapsedTime [s]'].agg(
    Durchschnitt_Zeit='mean',
    Median = 'median',
    Standardabweichung='std',
    Minimum='min', 
    Maximum='max'
).reset_index()

# Nach durchschnittlicher Abweichung sortieren
df10 = df10.sort_values(
    by='Durchschnitt_Zeit',
    ascending=True
)
df10

,Objekt,Durchschnitt_Zeit,Median,Standardabweichung,Minimum,Maximum
1,Kamera Packung,6.968883,6.173560,3.146117,3.665352,15.397066
0,Flasche,15.379744,16.250361,8.061147,5.261288,26.540390
2,Wasserwaage,16.788406,6.165205,29.725336,3.161710,100.590393

Unterschiede der Dimensionen

In [235]:
gefiltert35.head()

,Objekt,Yolo Label,Schwellwert,confidence,xSize [cm],ySize [cm],ElapsedTime [s],maxSide,minSide,Reale_Diagonale [cm],Abweichung [cm],Abweichung [%]
40,Würfel,carrot,0.35,0.369307,2.712696,2.657203,3.953543,2.3,2.3,3.252691,0.545813,16.780357
41,Würfel,carrot,0.35,0.431114,3.082000,3.081271,8.266110,2.3,2.3,3.252691,1.105400,33.984156
42,Würfel,cell phone,0.35,0.600833,2.793528,2.749698,5.875185,2.3,2.3,3.252691,0.667681,20.527042
43,Würfel,cell phone,0.35,0.396552,2.715040,2.691884,2.604727,2.3,2.3,3.252691,0.570816,17.549052
44,Würfel,cell phone,0.35,0.460230,2.775788,2.774226,3.255206,2.3,2.3,3.252691,0.671762,20.652508

In [236]:
gefiltert35['Abweichung_maxSide [cm]'] = abs(gefiltert35['maxSide'] - gefiltert35['xSize [cm]'])
gefiltert35['Abweichung_minSide [cm]'] = abs(gefiltert35['minSide'] - gefiltert35['ySize [cm]'])
gefiltert35['Abweichung_Gesamt'] = np.sqrt((gefiltert35['maxSide']-gefiltert35['xSize [cm]'])**2 + (gefiltert35['minSide']-gefiltert35['ySize [cm]'])**2 )
gefiltert35.head()

C:\Users\nicos\AppData\Local\Temp\ipykernel_9048\4024777263.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gefiltert35['Abweichung_maxSide [cm]'] = abs(gefiltert35['maxSide'] - gefiltert35['xSize [cm]'])
C:\Users\nicos\AppData\Local\Temp\ipykernel_9048\4024777263.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gefiltert35['Abweichung_minSide [cm]'] = abs(gefiltert35['minSide'] - gefiltert35['ySize [cm]'])
C:\Users\nicos\AppData\Local\Temp\ipykernel_9048\4024777263.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  gefiltert35['Abweichung_Gesamt'] = np.sqrt((gefiltert35['maxSide']-gefiltert35['xSize [cm]'])**2 + (gefiltert35['minSide']-gefiltert35['ySize [cm]'])**2 )

,Objekt,Yolo Label,Schwellwert,confidence,xSize [cm],ySize [cm],ElapsedTime [s],maxSide,minSide,Reale_Diagonale [cm],Abweichung [cm],Abweichung [%],Abweichung_maxSide [cm],Abweichung_minSide [cm],Abweichung_Gesamt
40,Würfel,carrot,0.35,0.369307,2.712696,2.657203,3.953543,2.3,2.3,3.252691,0.545813,16.780357,0.412696,0.357203,0.545813
41,Würfel,carrot,0.35,0.431114,3.082000,3.081271,8.266110,2.3,2.3,3.252691,1.105400,33.984156,0.782000,0.781271,1.105400
42,Würfel,cell phone,0.35,0.600833,2.793528,2.749698,5.875185,2.3,2.3,3.252691,0.667681,20.527042,0.493528,0.449698,0.667681
43,Würfel,cell phone,0.35,0.396552,2.715040,2.691884,2.604727,2.3,2.3,3.252691,0.570816,17.549052,0.415040,0.391884,0.570816
44,Würfel,cell phone,0.35,0.460230,2.775788,2.774226,3.255206,2.3,2.3,3.252691,0.671762,20.652508,0.475788,0.474226,0.671762

kleines Datenset so verändern dass selbe Objekte wie in großem sind

In [237]:
data_ObjektDim = gefiltert35.groupby('Objekt')['ElapsedTime [s]'].agg(
    Durchschnitt_Zeit='mean',
    Standardabweichung='std',
    Minimum='min', 
    Maximum='max'
).reset_index()

# Nach durchschnittlicher Abweichung sortieren
data_ObjektDim = data_ObjektDim.sort_values(
    by='Durchschnitt_Zeit',
    ascending=True
)
data_ObjektDim

,Objekt,Durchschnitt_Zeit,Standardabweichung,Minimum,Maximum
1,Metallplatte,4.441765,1.021754,3.227495,6.352299
4,Würfel,4.989213,2.339810,2.604727,8.433123
0,Ball,5.374182,2.078328,2.685750,9.484767
2,Schaumstoff Ding,7.911065,4.435779,4.635944,19.997053
3,Schraubenzieher,8.112295,7.280997,2.659599,25.552234